name: low_fps_recorder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

# Aggiungi questo blocco QUI:
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  # Usiamo ffmpeg_kit_flutter (pacchetto completo e piÃ¹ stabile)
  ffmpeg_kit_flutter_video: ^5.1.0 # Versione LTS stabile che non cerca dipendenze HTTPS esterne
  path_provider: ^2.1.1