name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Aggiornato da v3

      - name: Install Java
        uses: actions/setup-java@v4 # Aggiornato da v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Forza l'uso dell'ultima versione stabile
          # Rimuovi la riga flutter-version se vuoi sempre l'ultima, 
          # oppure metti '3.27.0' (una versione comune nel 2026)
          
      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        # Usiamo --split-per-abi per generare file più piccoli e facili da scaricare
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4 # FIX: Aggiornato da v3 a v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/*.apk
          compression-level: 0 # Opzionale: rende l'upload più veloce